-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 22, 2025 at 07:46 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 7.3.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pensive_nmcgenetics`
--

-- --------------------------------------------------------

--
-- Table structure for table `gene_page_desc`
--
CREATE TABLE `gene_page_desc` (
  `ID` int(11) NOT NULL,
  `uniqueid` varchar(20) NOT NULL,
  `gene` varchar(20) NOT NULL,
  `condition_name` varchar(200) NOT NULL,
  `gene_desc` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `gene_page_desc`
--

INSERT INTO `gene_page_desc` (`ID`, `uniqueid`, `gene`, `condition_name`, `gene_desc`) VALUES
(1, 'rs6564851', 'BCO1', 'Vitamin A', 'The protein encoded by this gene is\n                            a key enzyme in beta-carotene\n                            metabolism to vitamin A. It catalyzes\n                            the oxidative cleavage of &beta;-carotene into two retinal\n                            molecules. Diseases associated with\n                            BCO1 include Hypercarotenemia and\n                            Vitamin A Deficiency. Researches\n                            revealed that higher circulating &beta;-carotene levels in GG homozygotes depend on carotenoid intake while TT variants showed a reduced ability to convert beta carotene.'),
(2, 'rs4654748', 'NBPF3', 'Vitamin B6', 'This gene has been found in multiple studies to be associated with reduced levels of vitamin B6, possibly due to faster than normal clearance of this vitamin from the bloodstream. Individuals with a bad response had lower levels of B6 than those with a good response. Therefore, if your genotype is showing a bad or average response, you will get a result of “Optimize Intake.\" If your genotype is showing a good response, it is suggested that you \"Stay Balanced’ and maintain a healthy diet. The studies we report observed associations between vitamin levels and particular genotypes; however, that does not mean that your levels are out of balance.'),
(3, 'rs1801131', 'MTHFR', 'Vitamin B9', 'A relatively common variant in the MTHFR gene has been associated with lowered folate and elevated homocysteine levels in the blood. Hence, people with a bad response should optimize their intake of folate. People with a good response should \Stay Balanced\ and maintain a healthy diet. The studies we report observed associations between vitamin levels and particular genotypes; however, this does not mean that your levels are out of balance.\n'),
(4, 'rs602662', 'FUT2', 'Vitamin B12', 'The Fucosyltransferase 2 (FUT2) enzyme is encoded by the fucosyltransferase 2 gene and is involved in vitamin B12 absorption and transport between cells. Variants of this gene have been linked to low blood levels of vitamin B12 especially when consuming a vegetarian diet. Research shows that some individuals are at a greater risk than others for vitamin B12 deficiency based on the FUT2 gene. Since animal products are the primary sources of vitamin BI2, individuals following a vegetarian diet are at an even greater risk of vitamin B12 deficiency.'),
(5, 'rs33972313', 'SLC23A1', 'Vitamin C', 'After ingestion, the vitamin C in one\s diet gets transported across the cell membrane via transport proteins'),
(6, 'rs1544410', 'VDR', 'Vitamin D and Calcium', 'The VDR gene encodes the vitamin D receptor (VDR), a nuclear receptor protein that enables the body to respond to vitamin D, whether obtained from the diet or synthesized in the skin via sunlight exposure. This receptor is crucial for mediating the biological effects of vitamin D, particularly its active form, calcitriol (1α,25-dihydroxyvitamin D3). Moreover, activated VDR also stimulates renal (kidney) reabsorption of calcium and increases intestinal calcium absorption, helping maintain adequate serum calcium levels and preventing the release of calcium from bones.'),
(7, 'rs2282679', 'GC', 'Vitamin D and Calcium', 'The GC gene (officially named Group-Specific Component) encodes the vitamin D-binding protein (DBP) that binds and transports vitamin D metabolites ( e.g., cholecalciferol, calcifediol, calcitriol) in the bloodstream. DBP ensures these metabolites are delivered to target tissues, including the liver, kidneys, and bones, where they regulate calcium homeostasis.'),
(8, 'rs12272004', 'INTERGENIC', 'Vitamin E', 'The CD36 gene encodes a membrane protein known as cluster of differentiation 36 (CD3) that facilitates cellular uptake and absorption of vitamin E in the intestine and tissues whereas, the TTPA gene encodes the alpha-tocopherol transfer protein (α-TTP), a liver protein that is essential for the regulation and distribution of vitamin E (α-tocopherol) throughout the body.'),
(9, 'rs9923231', 'VKORC1', 'Vitamin K', 'The VKORC1 gene provides instructions for making a vitamin K epoxide reductase enzyme. It is made primarily in the liver. It helps turn on (activate) clotting proteins in the pathway that forms blood clots. Specifically, this enzyme converts one form of vitamin K into a different form of vitamin K that assists in activating clotting proteins.'),
(10, 'rs448378', 'MECOM', 'Magnesium', 'Your Genotype'),
(11, 'rs7965584', 'BRWD1P2', 'Magnesium', 'The MTHFR gene produces methylenetetrahrdrofolate reductase (MTHFR), which is a vital enzyme for folate usage in the body. MTHFR converts folate obtained from the diet to an active form of the nutrient that can be used by the body at the cellular level. Variations in the MTHFR gene determine the way individuals can utilize dietary folate.'),
(12, 'rs855791', 'TMPRSS6', 'Iron', 'The TMPRSS6 gene codes for the protein matriptase-2, which affects hepcidin levels that help to regulate iron balance. Genetic studies in humans have found that mutations of TMPRSS6 were associated with iron-refractory and iron deficiency anemia.'),
(13, 'rs1801133', 'MTHFR', 'Folic Acid', 'The MTHFR gene produces methylenetetrahrdrofolate reductase (MTHFR), which is a vital enzyme for folate usage in the body. MTHFR converts folate obtained from the diet to an active form of the nutrient that can be used by the body at the cellular level. Variations in the MTHFR gene determine the way individuals can utilize dietary folate.'),
(14, 'rs1050450', 'GPX1', 'Selenium', 'GPX1 enzyme plays an important role via the reduction of H<sub>2</sub>0<sub>2</sub> to H<sub>2</sub>0. GPX1 is a selenoprotein, meaning it incorporates selenium into its protein structure. This polymorphism reduces an individual\s ability to utilize selenium. That means that selenium intake needs to be assessed to afford protection to hydrogen peroxide-sensitive tissues'),
(15, 'rs174547', 'FADS1', 'Omega-3', 'FADS1 and FADS2 encode fatty acid desaturase enzymes that are crucial for the metabolism of PUFAs, including omega-3 and omega-6 fatty acids. These enzymes are involved in converting shorter-chain dietary omega-3 fatty acids like ALA into longer-chain, more biologically active forms such as EPA and docosahexaenoic acid DHA.'),
(16, 'rs1535', 'FADS2', 'Omega-3', 'FADS1 and FADS2 encode fatty acid desaturase enzymes that are crucial for the metabolism of PUFAs, including omega-3 and omega-6 fatty acids. These enzymes are involved in converting shorter-chain dietary omega-3 fatty acids like ALA into longer-chain, more biologically active forms such as EPA and docosahexaenoic acid DHA.'),
(17, 'rs1801282', 'PPARG', 'Carbohydrate', 'PPARG (Peroxisome proliferator-activated receptor gamma) is a nuclear receptor and transcription factor that plays a central role in carbohydrate metabolism by regulating genes involved in glucose homeostasis and insulin sensitivity.'),
(18, 'rs5082', 'APOA2', 'Saturated Fats', 'APOA2 is a gene that encodes apolipoprotein A-II, the second most abundant protein in high-density lipoprotein (HDL) particles, playing a role in lipid metabolism and HDL structure. APOA2 variants are associated with lower HDL ("good") cholesterol levels, especially in overweight or obese individuals, increasing the risk for heart disease and metabolic disorder.\n'),
(19, 'rs17366568', 'ADIPOQ', 'Mono Unsaturated Fats (MUFA)', 'ADIPOQ is the gene that encodes adiponectin, a hormone primarily produced by fat cells that is essential for regulating glucose and fatty acid metabolism, improving insulin sensitivity, and protecting against obesity,T2D, and cardiovascular disease. ADIPOQ association with adiponectin production that regulates insulin resistance, blood sugar control, and lipid profiles. These genetic differences may modify how the body responds to dietary fats, including MUFA, and can impact an individual\s risk for metabolic diseases.'),
(20, 'rs174547', 'FADS1', 'Poly Unsaturated Fats (PUFA)', 'FADS1 (Fatty Acid Desaturase 1) that encodes the enzyme delta-5 desaturase, which plays a crucial role in the metabolism of PUFAs. This enzyme catalyzes a key step in the conversion of shorter-chain PUFAs to their longer-chain, more biologically active forms, affecting the overall balance and levels of PUFAs in the body. Genetic variants in FADS1 can alter PUFA levels in the body, impacting cardiovascular health and disease risk by modulating the availability of these critical fatty acids.'),
(21, 'rs2322659', 'LCT', 'Lactose Intolerance', 'The LCT gene provides instructions for making the enzyme lactase, which is essential for digesting lactose, the sugar found in milk and dairy products. Lactase is produced in the small intestine and breaks down lactose into glucose and galactose (simpler form of sugar) so they can be absorbed by the body.\r\n\r\n'),
(22, 'rs762551', 'CYP1A2', 'Caffeine Sensitivity', 'The CYPIA2 gene produces an enzyme called cytochrome P450 1A2 (CYPIA2), which is the main enzyme responsible for breaking down caffeine in the body. Variations in the CYPIA2 gene affect the rate at which caffeine is broken down, which determines the impact of caffeine on heart health. Individuals who possess the Average or Low response of CYPIA2 break down caffeine more slowly and are at greater risk of high blood pressure and heart attack when caffeine intake is high. Those who have the good response actually have a lower risk of heart disease with moderate coffee consumption than those who consume no coffee at all.\r\n\r\n'),
(23, 'rs4343', 'ACE', 'Salt Sensitivity', 'ACE (Angiotensin-Converting Enzyme) is a key enzyme in the renin-angiotensin-aldosterone system, which regulates blood pressure and fluid balance; influencing how a person’s blood pressure responds to salt intake. In addition to ACE, AGT (Angiotensinogen) is an another protein produced by the liver and a precursor to angiotensin, interactive impact of ACE and AGT may have polygenic impact on blood pressure, when consuming a high-salt diet.\r\n\r\n'),
(24, 'rs699', 'AGT', 'Salt Sensitivity', 'About 38% of the general population carries an ACE gene variant that causes increased activity of this system, which leads to greater blood pressure increases in response to increased sodium in the blood. A genetic variant of the AGT gene leads to increased production of angiotensinogen. People carrying this variant are salt-sensitive, meaning they keep more sodium in the blood than non-carriers do. High sodium level increases blood volume, leading to increased blood pressure. Therefore, carriers of this AGT variant have a higher risk for hypertension. 83% Asians, showed response to this variant.\r\n\r\n'),
(25, 'rs7775228', 'HLADQ 2.2', 'Gluten Intolerance', 'The HLA genes produce a group of proteins called the human leukocyte antigen (HLA) complex, which is responsible for helping the immune system distinguish between the body’s own proteins and foreign, potentially harmful proteins. HLA genes are the most important genetic factor in gluten intolerance. People with celiac disease (about 99%) have altered variation of HLA gene and 60% of people with non-celiac gluten sensitivity also possess this variations compare to healthy individuals with the prevalence is 30%.\r\n\r\n'),
(26, 'rs2187668', 'HLADQ 2.5', 'Gluten Intolerance', 'The HLA genes produce a group of proteins called the human leukocyte antigen (HLA) complex, which are responsible for how the immune system distinguishes between the body’s own proteins and foreign, potentially harmful proteins. Research has shown that the HLA genes are the most important genetic allele of gluten intolerance. Approximately 99% of people with celiac disease and 60% of those with non-celiac gluten sensitivity have the DQ risk version of HLA, compared to only 30% of the general population.\r\n\r\n'),
(27, 'rs9939609', 'FTO', 'Pre Disposition to Obesity', 'FTO is Fat Mass and Obesity-Associated gene influences the regulation of hunger hormones (like ghrelin) and fat cell development, making it a key genetic factor in obesity susceptibility.  People with certain FTO gene variants may tend to have higher body mass index (BMI), increased appetite, and greater food intake, which raises their likelihood of becoming obese.'),
(28, 'rs894160', 'PLIN', 'Pre Disposition to Obesity', 'The PLIN gene encodes a protein perilipin that influences fat storage and its breakdown (lipolysis). Genetic variations in PLIN are linked to differences in regulation of body fat storage, risk of obesity, and metabolic health.'),
(29, 'rs5082', 'APOA2', 'Pre Disposition to Obesity', 'APOA2 is a Apolipoprotein A-II gene involved in fat metabolism and is a major component of HDL ("good") cholesterol. Certain variants of APOA2 are associated with higher risk of obesity, increased body fat, and altered eating habits.'),
(30, 'rs1042714', 'ADRB2', 'Response to Dieting', 'The ADRB2 gene encodes the beta-2 adrenergic receptor, a protein found on the surface of various cells, including fat cells (adipocytes), muscle, and the cardiovascular system. This receptor responds to hormones like adrenaline and noradrenaline, playing a key role in regulating energy expenditure, fat breakdown (lipolysis), and metabolism. Genetic variants of ADRB2 are associated with lipolysis in response to calorie restriction or dieting.'),
(31, 'rs17366568', 'ADIPOQ', 'Adiponectin Levels', 'Adiponectin, C1Q and Collagen Domain Containing (ADIPOQ) provides instructions for making adiponectin, a protein hormone (adipokine) produced mainly by fat cells (adipocytes). Adiponectin circulates in the blood and plays a crucial role in regulating how the body uses glucose (sugar) and breaks down fatty acids for energy. Genetic variations associated with ADIPOQ are  linked to obesity, insulin resistance, higher risk of type 2 diabetes, and cardiovascular disease.'),
(32, 'rs894160', 'PLIN', 'Waist Circumfrence Responses', 'Perilipin (PLIN) is the major protein surrounding lipid droplets in adipocytes and regulates adipocyte metabolism by modulating the interaction between lipases and triacylglycerol stores. A significant gene-diet interaction associated with obesity at the PLIN locus. In subjects with higher complex carbohydrate intake, the minor allele was protective against obesity (waist circumference), whereas in subjects with lower carbohydrate intake, the minor allele was associated with increased obesity.'),
(33, 'rs17782313', 'MC4R', 'Waist Circumfrence Responses', 'MC4R gene (Melanocortin 4 Receptor) encodes a receptor in the brain that is central to regulating appetite, energy balance, and body weight. This gene is a key part of the leptin-melanocortin pathway, which helps control how much food you eat and how your body stores fat. MC4R\s variants'),
(34, 'rs9939609', 'FTO', 'Weight Regain Risk', 'FTO is Fat Mass and Obesity-Associated gene influences the regulation of hunger hormones (like ghrelin) and fat cell development, making it a key genetic factor in obesity susceptibility.  People with certain FTO gene variants may tend to have higher body mass index (BMI), increased appetite, and greater food intake, which raises their likelihood of becoming obese.'),
(35, 'rs1801282', 'PPARG', 'Weight Regain Risk', 'PPARG (Peroxisome proliferator-activated receptor gamma) The PPARG gene is involved in the formation of fat cells. This gene is mainly found in fat tissue. Because of its involvement in the formation of fat, PPARG can impact weight management and body composition.'),
(36, 'rs11549465', 'HIF1A', 'Cellulite Pre-Disposition', 'Hypoxia-Inducible Factor 1 Alpha (HIF1A) gene encodes a protein that helps cells respond to low oxygen levels (hypoxia), a condition common in areas of poor blood circulation and fat accumulation, such as cellulite-affected tissue. HIF1A are associated with a lower risk of developing cellulite. Individuals with this variant have about a 40% reduced chance of developing cellulite, possibly due to improved tissue response to hypoxia and less fibrosis in the skin and connective tissue.'),
(37, 'rs4343', 'ACE', 'Cellulite Pre-Disposition', 'ACE gene increases their blood pressure and limits oxygen supply to their tissues. Limiting the oxygen supply to fat tissue stimulates fat tissue deposits. This is why, even lean women with the deletion variant are more likely to have cellulite.'),
(38, 'rs1801282', 'PPARG', 'FAT Storage', 'Energy storage is a mechanism used by humans to deal with food shortage. In the presence of excess energy, (PPARG) trigger its storage by promoting fat synthesis. In those with the PPARG variant, the body isn’t getting the normal signal from polyunsaturated fatty acids that should make the fat cells fatter.'),
(39, 'rs1800497', 'ANKKI/DRD2', 'Eating Behaviour Trait', 'Ankyrin repeat and kinase domain containing 1 (ANKK1) and dopamine D2 receptors (DRD2) genes plays a crucial role in regulating dopamine signaling in the brain’s reward pathways. The change in the dopamine signaling may controls compulsive eating behaviors, overeating, and obesity, as individuals may eat more to compensate for a less responsive reward system'),
(40, 'rs838133', 'FGF21', 'Sweet Perception', 'Fibroblast Growth Factor 21 (FGF21) is a liver-derived hormone that influences sweet perception by decreasing sensitivity to sweet tastes while increasing preference for sweet foods, particularly in people with T2D. It acts on the brain’s reward pathways and is influenced by both dietary sugar intake and genetic variation in the FGF21 gene'),
(41, 'rs713598', 'TAS2R38(1)', 'Bitter Taste Perception', 'Taste 2 receptor member 38 (TAS2R38) encodes a bitter taste receptor that plays a central role in human sensitivity to certain bitter compounds. TAS2R38 is part of the TAS2R family of G protein-coupled receptors located on taste receptor cells in the tongue. Genetic variations in TAS2R38 influence bitter taste sensitivity influence food choices, nutrient intake, and may affect health outcomes.'),
(42, 'rs1726866', 'TAS2R38(2)', 'Bitter Taste Perception', 'Taste 2 receptor member 38 (TAS2R38) encodes a bitter taste receptor that plays a central role in human sensitivity to certain bitter compounds. TAS2R38 is part of the TAS2R family of G protein-coupled receptors located on taste receptor cells in the tongue. Genetic variations in TAS2R38 influence bitter taste sensitivity influence food choices, nutrient intake, and may affect health outcomes.'),
(43, 'rs9939609', 'FTO', 'Satiety', 'FTO gene also regulates appetite and satiety. Variants in the FTO gene are associated with reduced satiety responsiveness, signifying individuals with these variants tend to feel less full after eating and are more likely to overeat. Variations in FTO regulates satiety that increases tendency to have higher caloric intake may lead to greater risk of obesity.\r\n\r\n'),
(44, 'rs2025804', 'LEPR', 'Snacking Behaviour', 'LEPR gene encodes the leptin receptor, a key protein involved in regulating hunger and satiety signals in the brain. When leptin binds to this receptor, it helps suppress appetite and reduce food intake. Genetic variants in the LEPR gene can impair this signaling pathway, leading to weaker satiety responses and increased hunger, which can promote overeating and frequent snacking.'),
(45, 'rs4420638', 'APOE', 'Elevated LDL Cholestrol', 'Apolipoprotein E (ApoE) is one of the protein that the body uses to transport fats (lipids) in the bloodstream from one tissue or cell type to another. It is essential for healthy metabolism of cholesterol and triglycerides. Lipoprotein particles containing ApoE carry both cholesterol and triglycerides. Its primary purpose is to promote clearance of triglyceride-rich lipoproteins from the circulation.'),
(46, 'rs662799', 'APOA5', 'Elevated Triglycerides', 'APOA5 (Apolipoprotein A5) is a gene that encodes a protein crucial for regulating plasma triglyceride levels. Variants in the APOA5 gene are strongly associated with differences in blood triglyceride concentrations, making it a key genetic determinant of elevated triglycerides-a major risk factor for cardiovascular disease.'),
(47, 'rs780094', 'GCKR', 'Higher Serum Triglycerides', 'A GCKR gene risk variant strongly influences lipid overproduction. GCKR encoding the glucokinase regulatory protein, contributes to the risk of type-2 diabetes and dyslipidemia in multiple populations. The risk allele is associated with the following traits: higher levels of fasting serum triacylglycerol, impaired fasting and OGTT-related insulin release, dyslipidemia and somewhat reduced risk of type-2 diabetes (This is a classic example of a genetic trade-off between glucose and lipid metabolism).'),
(48, 'rs708272', 'CETP', 'Higher HDL Cholestrol', 'Cholesteryl ester transfer protein (CETP) is a protein made by the liver and found in the blood, mostly attached to HDL (the "good" cholesterol). CETP helps manage cholesterol levels by moving cholesterol from HDL to other types of cholesterol, like VLDL and LDL (the "bad" cholesterols), and in return, it moves triglycerides to HDL.'),
(49, 'rs1800588', 'LIPC', 'Higher HDL Cholestrol', 'LIPC (lipase C) is a gene that encodes the enzyme hepatic lipase. This enzyme is involved in the conversion of larger, cholesterol into smaller HDL particles. These simpler form of HDL remove excess cholesterol from tissues, including the walls of arteries, and transports it to the liver for disposal, a process known as reverse cholesterol transport. This function helps to protect against atherosclerosis and cardiovascular disease.'),
(50, 'rs9939609', 'FTO', 'BMI And Waist Circumfrence', 'FTO is Fat Mass and Obesity-Associated gene influences the regulation of hunger hormones (like ghrelin) and fat cell development, making it a key genetic factor in obesity susceptibility.  People with certain FTO gene variants may tend to have higher body mass index (BMI), increased appetite, and greater food intake, which raises their likelihood of becoming obese'),
(51, 'rs7566605', 'INSIG2', 'Response to Strength/Resistance Training', 'The Insulin signaling protein type 2 gene (INSIG2) is associated with the synthesis of INSIG2 protein which interacts with transcription factors, activating the said synthesis of cholesterol and fatty acids. The variants of the INSIG2 gene have been shown to be associated with body fat accumulation. Specific alleles of this gene are known to either increase or decrease INSIG2 protein levels which are associated with subcutaneous fat accumulation upon exercising.'),
(52, 'rs1042713', 'ADRB2', 'Adernaline Response', 'The B2 adrenergic receptor 2 (ADRB2) gene is associated with the synthesis of B2 adrenergic receptor 2, a cell membrane’ spanning receptor that binds to adrenaline. Specific alleles of this gene are known to either increase or decrease the sensitivity of the body to the effects of adrenaline. Variants of the gene are shown to be associated with changes in the heart rate, size of the bronchioles, transport of oxygen and utilization of fat during exercise.'),
(53, 'rs1042714', 'ADRB2', 'Adernaline Response', 'Your Genotype'),
(54, 'rs12150660', 'SHBG', 'Testosterone Response', 'SHBG codes for a protein that binds testosterone in the blood. With additional experiments, the researchers observed lower testosterone levels were also linked to lower concentrations of SHBG.'),
(55, 'rs6258', 'SHBG', 'Testosterone Response', 'SHBG codes for a protein that binds testosterone in the blood. With additional experiments, the researchers observed lower testosterone levels were also linked to lower concentrations of SHBG.'),
(56, 'rs1042714', 'ADRB2', 'Fat Metabolism', 'This ADRB2 receptor protein is involved in the mobilization of fat from fat cells for energy in response to catecholamines, and modulates lipolysis during exercise. The allele has been associated with obesity, and carriers are more likely to gain and regain weight and lose weight more slowly. These carriers are less able to mobilize fat stores in response to exercise.'),
(57, 'rs1800588', 'LIPC', 'HDL Cholestrol Response', 'LIPC (lipase C) is a gene that encodes the enzyme hepatic lipase. This enzyme is involved in the conversion of larger, cholesterol into smaller HDL particles. These simpler form of HDL remove excess cholesterol from tissues, including the walls of arteries, and transports it to the liver for disposal, a process known as reverse cholesterol transport. This function helps to protect against atherosclerosis and cardiovascular disease.'),
(58, 'rs4341', 'ACE', 'ACT3 (PP)', 'ACE, or angiotensin-converting enzyme, is a key enzyme in the renin angiotensin system (RAS) that regulates blood pressure and fluid balance in the body. Certain ACE gene variants are associated with differences in endurance, people with specific ACE gene profiles may favors in either endurance or power-based activities, influencing athletic performance.'),
(59, 'rs699', 'AGT', 'AGT (PP)', 'This gene plays a role in how well we respond to power-based training, and so appears in our power-endurance profile, and also plays a role in blood pressure control. One of the studies showing the effect of this gene on training response was published in 2009. Certain genotype of AGT was significantly higher in the power group of athletes than either the endurance or non-athlete groups. If a person had particular genotype, they were about 1.6 times more likely to be in the power group than any of the others.'),
(60, 'rs4253778', 'PPARA', 'PPARA (PP)', 'PPARA, a gene that affects how well we can respond to different types of training, and as a result appears in our power - endurance algorithm. PPARA creates peroxisome proliferator- activated receptor alpha, a protein which activates other genes, as well as being a regulator of fatty acid oxidation during exercise.The gene is activated when cells experience low energy levels, such as during intense physical activity or periods of fasting (dieting).'),
(61, 'rs1800795', 'IL6', 'IL6 (PP)', 'Interleukin-6 (IL-6) functions both as a pro-inflammatory cytokine and an anti-inflammatory myokine, playing a dual role in immune response and muscle metabolism. During and after exercise, IL-6 is released in significant amounts from muscle tissue, where it contributes to energy regulation by stimulating glucose release from the liver and promoting fat breakdown from adipose tissue.'),
(62, 'rs540874', 'ACTN3', 'ACTN3 (PP)', 'It\s one of the most well studied genes with regards to sporting performance. ACTN3 codes for a protein that is found exclusively in the fastest kind of muscle fibres'),
(63, 'rs2070744', 'NOS3', 'NOS3 (PP)', 'Nitric oxide synthase 3 (NOS3) is an enzyme which is responsible for the production of the small molecule nitric oxide (NO) and is encoded for by the NOS3 gene. NOS3 is predominantly expressed in the endothelial tissue which lines the circulatory system and heart. Individuals with optimal NOS3 function often exhibit better cardiovascular fitness and vascular responsiveness to exercise.'),
(64, 'rs4341', 'ACE', 'ACE3 (EP)', 'ACE, or angiotensin-converting enzyme, is a key enzyme in the renin angiotensin system (RAS) that regulates blood pressure and fluid balance in the body. Certain ACE gene variants are associated with differences in endurance, people with specific ACE gene profiles may favors in either endurance or power-based activities, influencing athletic performance.'),
(65, 'rs4253778', 'PPARA', 'PPARA (EP)', 'Peroxisome Proliferator- Activated Receptor Alpha (PPARA), a protein associated with the activation of other genes and also in regulation of fatty acid oxidation during exercise. A lack of energy in the cells activate this gene like during endurance exercises or when fasting.'),
(66, 'rs1042713', 'ADRB2', 'ADRB2 (EP)', 'Beta(2)-adrenergic receptors are expressed throughout the body and serve as receptors for the natural stimulant hormones called catecholamines epinephrine (adrenaline) and norepinephrine. Variants of the gene are shown to be associated with changes in the heart rate, size of the bronchioles, transport of oxygen and utilization of fat during exercise.'),
(67, 'rs7181866', 'NRF2', 'NRF2 (EP)', 'The GA-binding protein (GABP) gene, also referred to as Nuclear Respiratory Factor 2 (NRF2), encodes a transcription factor crucial for cellular energy production. NRF2 protein has been linked to enhanced endurance. By boosting respiratory capacity and accelerating ATP production during exercise, NRF2 plays a key role in optimizing energy availability and supporting superior athletic performance.'),
(68, 'rs8192678', 'PPARGC1A', 'PPARGC1A (AC)', 'The PPARGCIA gene is associated with the synthesis of peroxisome proliferator-activated receptor gamma coactivator 1-alpha (PGC-1a), which is associated with mitochondrial biogenesis or the production of new mitochondria within the muscle. Research studies shown that some allele has been associated with VO2 max, endurance performance and exercise efficiency.'),
(69, 'rs2010963', 'VEGFA', 'VEGFA (AC)', 'The Vascular Endothelial Growth Factor (VEGFA) gene is associated with the synthesis VEGFA, a molecule associated with the formation of new blood vessels (angiogenesis) upon training. This adaptation allows the body to increase supply of nutrients and oxygen to the trained muscles as well as remove waste products.'),
(70, 'rs1042713', 'ADRB2', 'ADRB2 (AC)', 'Beta(2)-adrenergic receptors are expressed throughout the body and serve as receptors for the natural stimulant hormones. Beta- adrenergic receptors are found in fat cells, liver and skeletal muscle where they are involved in fat mobilization, blood glucose levels and in vasodilation.'),
(71, 'rs1042714', 'ADRB2', 'ADRB2 (AC)', 'Variants of the gene are shown to be associated with changes in the heart rate, size of the bronchioles, transport of oxygen and utilization of fat during exercise. People with the particular variant (GIn27) of the gene were associated with better aerobic capacity and increase in VO2 max after aerobic training.\r\n\r\n'),
(72, 'rs1130214', 'AKT1', 'AKT1 (AC)', 'RAC-alpha serine/threonine-protein kinase is an enzyme that in humans is encoded by the AKT1 gene. A version of this gene that is linked to better resting metabolic factors and greater increases in VO2 max in response to aerobic exercise.'),
(73, 'rs2016520', 'PPARD', 'PPARD (ANC)', 'PPARD (peroxisome proliferator-activated receptor delta) is a gene that encodes the PPAR-delta protein, a nuclear receptor involved in regulating genes related to energy metabolism, lipid oxidation, and muscle fiber composition. Genetic variants in PPARD can influence how muscles respond to anaerobic exercise by affecting glucose utilization, muscle adaptation, and recovery, ultimately shaping an individual\'s capacity for high-intensity, short-duration physical performance.'),
(74, 'rs1800795', 'IL6', 'Injury Risk', 'Interleukin 6 (IL-6), promptly and transiently produced in response to infections and tissue-injuries, contributes to host defense through the stimulation of acute phase responses, hematopoiesis, & immune reactions. The IL-6 response to injury is supposed to be uniquely consistent and related to injury severity'),
(75, 'rs2234693', 'ESR1', 'Muscle Injury', 'Muscle stiffness, a risk factor for muscle injury, is lower in females than in males, implying that sex-related genetic polymorphisms influence muscle injury associated with muscle stiffness. In humans, Estrogen receptor alpha is encoded by the gene ESR1 (Estrogen Receptor 1). Particular allele of this gene provides protection against muscle injury by lowering muscle stiffness.'),
(76, 'rs1205', 'CRP', 'Recovery', 'CRP gene encodes C-reactive protein, a key biomarker and mediator of inflammation and tissue repair. CRP plays a dynamic role: its levels rise rapidly during the acute inflammatory phase following tissue injury, supporting hemostasis and immune defense, then gradually decline as inflammation resolves and tissue regeneration begins'),
(77, 'rs679620', 'MMP3', 'Achilles Tendinopathy Risk', 'MMP3 is a proteolytic enzyme involved in the breakdown and remodeling of extracellular matrix components in tendon tissue. In Achilles tendinopathy, MMP3 plays a key role in the degradation of collagen and other matrix proteins, contributing to tendon inflammation and structural deterioration.'),
(78, 'rs4880', 'SOD2', 'Oxidative Stress (IR)', 'Superoxide dismutase 2 is an enzyme that functions as an antioxidant within the mitochondria. It catalyzes the breakdown of a toxic substance, superoxide, into less toxic compounds. Overall, SOD2 protects against oxidative stress.'),
(79, 'rs1800012', 'COL1A1', 'Ligament Rupture Risk', 'The COL1A1 gene encodes the alpha-1 chain of type I collagen, the principal structural protein in ligaments, tendons, bone, and other connective tissues. Genetic variations in COL1A1 that encodes Sp1 binding proteins have been associated with susceptibility to ligament ruptures, including anterior cruciate ligament (ACL) injuries.'),
(80, 'rs4646422', 'CYP1A1', 'Detoxification Phase 1', 'CYP1A1 is a crucial enzyme in Phase I detoxification, where the body begins breaking down toxins into intermediate forms. This enzyme helps process environmental pollutants such as cigarette smoke, exhaust fumes, and charred meats specifically, substances called polycyclic aromatic hydrocarbons (PAHs). Genetic variations in the CYP1A1 gene can lead to either reduced or increased enzyme activity that affect how effectively the body handles toxins and hormones.'),
(81, 'rs1056836', 'CYP1B1', 'Detoxification Phase 1', 'CYP1B1 is a key enzyme involved in Phase I detoxification. During this phase, CYP1B1 helps convert harmful chemicals from the environment such as pollutants, smoke, and pesticides as well as natural substances like estrogen, into intermediate forms.  Genetic variations in the CYP1B1 gene can increase enzyme activity, leading to a higher production of these reactive intermediates. If not neutralized in Phase II, these compounds may damage cells and increase the risk of hormone related disorders.'),
(82, 'rs4148323', 'UGT1A1', 'Detoxification Phase 2', 'UGTIAI is an enzyme of the glucuronidation pathway, that transforms steroids, bilirubin, hormones, and drugs into water-soluble excretable metabolites. The most common deficiency of UGTIA1 enzyme is Gilbert\s syndrome'),
(83, 'rs1695', 'GSTP1', 'Detoxification Phase 2', '<p>Glutathione S-transferases (GSTs) catalyze the transfer of glutathione - an important cellular antioxidant, to xenobiotic compounds.</p>\r\n               <p>Apart from processing xenobiotics, GSTs protect against oxidative stress, and function as a defense against reactive oxygen species (superoxide radical and hydrogen peroxide) that arise through normal metabolic processes.</p>\r\n               <p>GSTs are widely distributed throughout the body and can be found in liver, kidney,</p>\r\n               <p>brain, pancreas, testis, heart, lung, small intestine, skeletal muscle, prostate and spleen</p>'),
(84, 'rs3957357', 'GSTA1', 'Detoxification Phase 2', '<p>Glutathione S-transferases (GSTs) catalyze the transfer of glutathione - an important cellular antioxidant, to xenobiotic compounds.</p>\r\n               <p>Apart from processing xenobiotics, GSTs protect against oxidative stress, and function as a defense against reactive oxygen species (superoxide radical and hydrogen peroxide) that arise through normal metabolic processes.</p>\r\n               <p>GSTs are widely distributed throughout the body and can be found in liver, kidney,</p>\r\n               <p>brain, pancreas, testis, heart, lung, small intestine, skeletal muscle, prostate and spleen</p>'),
(85, 'rs1800566', 'NQO1', 'Detoxification Phase 2', 'NQO1 is involved in breaking down exogenous (outside) toxins such as benzene and some chemotherapy drugs. Benzene, a carcinogen, is found in gasoline fumes, laundry detergent, furniture wax, industrial uses, pesticides, and smoke. NQO1 is also involved in cellular defense against oxidative stress, reduction of CoQ, and reduction of vitamin K.'),
(86, 'rs4680', 'COMT', 'Detoxification Phase 2', 'COMT (Catechol-O-methyltransferase) is a major Phase II detoxification enzyme responsible for the methylation neurotransmitters (like dopamine, norepinephrine, and epinephrine), catechol estrogens, and certain drugs or environmental toxins making them less reactive and more water-soluble. This modification allows the body to safely eliminate them through urine or bile.'),
(87, 'rs1799929', 'NAT2', 'Detoxification Phase 2', 'NAT2 gene, potentially encoding a variant detoxifying protein known as an N- acetyltransferase. NAT2 variants both activate and deactivate various pharmaceutical drugs and carcinogens, as well as detoxifies caffeine. Variants are associated with slow activity and increased incidence of cancer and drug toxicity.'),
(88, 'rs662', 'PON1', 'Detoxification Phase 2', 'PON1 (Paraoxonase 1), variants of this enzyme decrease activity and therefore increase risk of exposure to harmful chemicals, oxides lipids and the development of atherosclerosis. Since PON1 enzymes are responsible for the detoxification of organophosphates (the base for insecticides herbicides, and nerve agents), oxidized lipids and also aromatic esters.'),
(89, 'rs4880', 'SOD2', 'Oxidative Stress', 'Superoxide dismutase (SOD) is the gene that codes for the copper-zinc superoxide dismutase enzymes which help protect against oxidative stress and detoxify reactive oxygen species. SOD2 variants can result in a predisposition to oxidative stress. Ensure adequate intake of the co-factor manganese.'),
(90, 'rs1050450', 'GPX1', 'Oxidative Stress', 'The GPX gene encodes the enzyme glutathione peroxidase, which catalyzes the reduction of peroxides and hydrogen peroxide. GPX plays a role in protecting the body against oxidative stress.'),
(91, 'rs1800566', 'NQO1', 'Oxidative Stress', 'NQO1 is also involved in cellular defense against oxidative stress, reduction of CoQ, and reduction of vitamin K. In the reduction (chemistry meaning, think redox reaction) of Vitamin K, NQO1 is mostly involved in turning K3 into the form that is active in blood clotting and bone building.'),
(92, 'rs7903146', 'TCF7L2', 'Insulin Sensitivity', 'Transcription factor 7-like 2 (TCF7L2) gene influences pancreatic -cell function. Decreased Insulin secretion affecting the individual\s ability to remove glucose from the blood based on the TCF7L2.'),
(93, 'rs9939609', 'FTO', 'Insulin Sensitivity', 'FTO gene influences insulin sensitivity primarily through its impact on adiposity and metabolic regulation. FTO gene variants reduce insulin sensitivity by disrupting insulin signaling and promoting fat accumulation, increasing the risk of insulin resistance and metabolic disease.'),
(94, 'rs4988235', 'MCM6', 'Lactose Intolerance', 'The MCM6 gene helps to control the LCT gene, which makes the enzyme lactase needed to digest milk sugar (lactose). Some people have special changes (variants) in the MCM6 gene that keep the LCT gene “switched on” even after childhood, so they can keep digesting milk as adults. If you don’t have these changes, your body makes less lactase as you grow up, which can lead to lactose intolerance.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `gene_page_desc`
--
ALTER TABLE `gene_page_desc`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `gene_page_desc`
--
ALTER TABLE `gene_page_desc`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=95;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
